spring:
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/photobook
    username: prod
    password: prod
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      file-size-threshold: 2KB
      max-request-size: 30MB
jwt:
  secret: bezKoderSecretKey
  expiration: 86400000

s3:
  buckets:
    compressed: photobook-compressed
    uncompressed: photobook-uncompressed
