spring:
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/photobook
    username: prod
    password: prod
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
jwt:
  secret: bezKoderSecretKey
  expiration: 86400000
